<?php 

	session_start();	
	//session_regenerate_id(true);

	// define PATH url 
	DEFINE('PATH',	realpath(dirname(__FILE__)));
	// global vars
	global $UserID, $serverID, $LANG, $keyLANG,  $session, $avatarUser, $pageFooter, $NA, $rankID, $bodyHTML, $menuHTML, $pageHeader, $classMain;
	// define main lenguage [default]
	$keyLANG = 'es';


	// debug mode [comments = off]
	error_reporting(E_ALL|E_STRICT);

	#
	# REQUIRE FILES TO CONECTION
	#

		require PATH.'/kernel/database.php'; 								
		require PATH.'/kernel/core/functions.php'; 				

	#
	# REQUIRE CLASS USERS
	#
		require PATH.'/kernel/class/session.php'; 

	#
	# CONTROL USER SESSION ID
	#

		// PDO start name instance 
		$PDO_INSTANCE = 'SB_CR';

		// check user ID is exist
		if(@$_SESSION['id'] != null) {

			// begin class session
			$session = new PHPSession($PDO_INSTANCE);
			$session->gc(300);

			// start session ID in @UserID
			$UserID = $_SESSION['id'];
			$session->read($UserID);

		} else { $UserID = null; $serverID = null; }

	#
	# DEFINE BASIC CONFIG
	#

		$config_data = $db->query("SELECT * FROM config");
		$config_ 	 = $db->single();

		DEFINE('TITLE', $config_['title']);
		DEFINE('SLOGAN', $config_['slogan']);
		DEFINE('URL', $config_['url']);
		DEFINE('TIME_ZONE', $config_['time_zone']);
		DEFINE('LIMIT_LOGINS', $config_['limit_login']);
		DEFINE('SBPANEL', $config_['sbpanel']);
		
		DEFINE('EMAILCONTACT', $config_['email_contact']);
		DEFINE('GOOGLEAPI', $config_['google_api']);

		$db->CloseConnection();

	#
	# TIME DEFAULT ZONE
	#
	
		@date_default_timezone_set(TIME_ZONE);	

	#
	# REQUIRE FILES TO USER CONTROL SESSION [class]
	#

		require PATH.'/kernel/class/users.php';
      // $avatarD avatar default
      $avatarD = URL."/assets/images/avatars/default.jpg";
		if( $UserID >= 1 ) {

			// session exist (?) [review]
			@$User->session($UserID);
		   // search data serverID
		   $serverID = $User->user( $UserID, 'server' );
			$rankID = $User->user($UserID, 'rank');
			$goLogout = null;
			$avatarU = $User->user($UserID, "avatar");
			if( $avatarU != null ) { $avatarUser = URL."/assets/images/avatars/".$avatarU; } else { $avatarUser = $avatarD; }

			// is online now )?
			$isLogin = $User->user($UserID, 'isonline');
			if( $isLogin == 0 ) {

				// remove session
				unset($_SESSION['id']); @session_destroy();

			}

		} else { 

			$goLogout = @$_SESSION['gologout'];
			$serverID = $rankID = null;
			$avatarUser = $avatarD;

		}

		// check off sessions
		$User->session(0);
	
	#
	# REQUIRE FILES TO PHPMAILER [send mails]
	#

        require PATH.'/kernel/class/phpmailer/PHPMailer.php';
        require PATH.'/kernel/class/phpmailer/SMTP.php';
        require PATH.'/kernel/class/phpmailer/Exception.php';		

	#
	# REQUIRE OTHERS FILES
	#
		// class to BBCODE 
		require PATH.'/kernel/class/bbcode/SBBCodeParser.php'; 								
		// class uploads files 						
		require PATH.'/kernel/class/upload_image.php'; 	

		// vars system
		$datetime = $CR->time('datetime');
		$date = $CR->time('date');
		$time = $CR->time('time');
		$ip = $CR->ip();
		$navegator = $CR->navegator();
		$page = $filtrandoPor = $pageFooter = $pgH2 = $ssOff = null;
		$bodyHTML = $classMain = $pageHeader = $menuHTML = "home";

		// initial vars
		$navBrand = $navCrumb = "";
		$dataPage = "landing";
		$closeModal = $CR->updateJS(" modalX(); ", 0);
		$selectOption = "Selecciona una opción";
		
		$pageTitle = TITLE;
		$metaSEO = null;

		// get path sbpanel
		$pathSB = str_replace(URL, "", SBPANEL);
		$pathSB = str_replace("/", "", $pathSB);

		// prepared vars tu database backup
		$db_host = DB_HOST;
		$db_name = DB_NAME;
		$db_user = DB_USER;
		$db_pass = DB_PASS;

?>